### PR TITLE
feat: test context aware policy

### PR DESCRIPTION
**Pull request by flavio**
Add a test for context aware policies

Warning: this requires latest 1.6.0 RC plus https://github.com/kubewarden/helm-charts/pull/223

Depends on: https://github.com/kubewarden/helm-charts/pull/225

### CODE REVIEW

**Comment by flavio** [comment]
@kravciak can you take a look please?

**Review by viccuad — APPROVED** [review]

**Comment by flavio** [comment]
The tests are passing locally

**Comment by kravciak** [comment]
hi, saw notification only after you merged, sorry for no review...
I noticed that test is failing in our CI - https://github.com/kubewarden/kubewarden-controller/actions/runs/4716116290/jobs/8363574797#step:5:47 - will this be fixed when we release?

**Comment by flavio** [comment]
Yes, this will be fixed. The fix is done inside of the helm charts

**Pull request merged**
